name: CI Pull Requests
on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js 16
        uses: actions/setup-node@master
        with:
          node-version: 16
      - name: yarn install
        run: yarn install
      - name: Danger
        run: yarn danger ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
